### ISSUE TITLE
Can't create user using Signup form

### ISSUE THREAD

**Issue by Rajan** [strongloop/loopback-example-user-management#9]
loopback deprecated Routes "/methods" and "/models" are considered dangerous and should not be used.
Disable them by setting "legacyExplorer=false" in "server/config.json" or via "app.set()". node_modules/loopback/node_modules/express/lib/router/layer.js:82:5
> user.afterRemote triggered
/var/www/loopback-faq-user-management/common/models/user.js:21
        next(err);
        ^
ReferenceError: next is not defined
    at /var/www/loopback-faq-user-management/common/models/user.js:21:9
    at /var/www/loopback-faq-user-management/node_modules/loopback/common/models/user.js:404:11
    at /var/www/loopback-faq-user-management/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/src/smtp-transport.js:102:28
    at SMTPConnection._actionAUTHComplete (/var/www/loopback-faq-user-management/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:838:16)
    at SMTPConnection.<anonymous> (/var/www/loopback-faq-user-management/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:242:22)
    at SMTPConnection._processResponse (/var/www/loopback-faq-user-management/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:506:16)
    at SMTPConnection._onData (/var/www/loopback-faq-user-management/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:356:10)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)

**Comment by kpullen** [comment]
@Rajan:

> loopback deprecated Routes "/methods" and "/models" are considered dangerous and should not be used.
Disable them by setting "legacyExplorer=false" in "server/config.json" or via "app.set()". 

 This problem can be solved by editing `server/config.json` and setting (or adding and then setting) `legacyExplorer` to false.

> node_modules/loopback/node_modules/express/lib/router/layer.js:82:5

> user.afterRemote triggered
/var/www/loopback-faq-user-management/common/models/user.js:21
next(err);
^
ReferenceError: next is not defined
at /var/www/loopback-faq-user-management/common/models/user.js:21:9
at /var/www/loopback-faq-user-management/node_modules/loopback/common/models/user.js:404:11
at /var/www/loopback-faq-user-management/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/src/smtp-transport.js:102:28
at SMTPConnection._actionAUTHComplete (/var/www/loopback-faq-user-management/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:838:16)
at SMTPConnection. (/var/www/loopback-faq-user-management/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:242:22)
at SMTPConnection._processResponse (/var/www/loopback-faq-user-management/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:506:16)
at SMTPConnection._onData (/var/www/loopback-faq-user-management/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:356:10)
at TLSSocket.emit (events.js:107:17)
at readableAddChunk (_stream_readable.js:163:16)
at TLSSocket.Readable.push (_stream_readable.js:126:10)

I believe you received the error because `server/models/user.js` calls `next()` but next is undefined. That's a problem, but not a huge one; `afterRemote`'s callback signature accepts next as the third parameter. Try adding that parameter to the callback.

I solved these problems on my [fork](https://github.com/kpullen/loopback-faq-user-management), but I haven't had a chance to separate them from another feature I added: Upgrading User without creating a new model. I'll try and fix it up and send a pull request, but in the meantime you can check out my fork for example fixes to these problems.

Also, if you haven't, check out the documentation for Loopback's [remote operations](http://docs.strongloop.com/display/public/LB/Remote+hooks).

**Comment by superkhau** [comment]
Fixed warning in #20
